# RetroMart Application Properties
spring.application.name=retro
spring.web.resources.static-locations=classpath:/META-INF/resources/,\
classpath:/resources/,\
classpath:/static/,\
classpath:/public/,\
file:./uploads/
